version: '3'
services:
    mymongo:
        image: mongo
        environment:    # 환경변수를 정의합니다.
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: abc123
        ports:
            - 27017:27017
        
